### ISSUE TITLE
The extension isn't implementing ExtensionInterface

### ISSUE THREAD

**Issue by RedLucas** [twigphp/inky-extension#4]
```Symfony\Component\DependencyInjection\Exception\LogicException: Service '{service name}' for consumer 'twig' does not implement Twig\Extension\ExtensionInterface```

This is only a problem seemingly in twig 1.34. Where AbstractExtension doesn't implement ExtensionInterface.

**Comment by RedLucas** [comment]
https://github.com/twigphp/inky-extension/pull/5

**Comment by garak** [comment]
But I see that in Twig 1.34 `AbstractExtension` is implementing `Twig_ExtensionInterface`, so it should work anyway
