### ISSUE TITLE
Upgrade pinky version

### ISSUE THREAD

**Issue by chapa** [twigphp/inky-extension#6]
Pinky requires the XSL PHP extension to be installed (https://github.com/lorenzo/pinky/issues/9), but it didn't required it in its composer.json before 1.0.4 (https://github.com/lorenzo/pinky/commit/9a330a41147b25b344a62a6f1806cb40faa613c6).

As I didn't have this extension installed and just ran `composer require twig/inky-extension`, and the error I got wasn't very clear :
```
An exception has been thrown during the rendering of a template ("Warning: Use of undefined constant XSL_SECPREF_READ_FILE - assumed 'XSL_SECPREF_READ_FILE' (this will throw an Error in a future version of PHP)").
```

Maybe you should update the dependency version to at least 1.0.4 so we can't install it without having ext-xsl installed

**Comment by garak** [comment]
So, why did you install a version before 1.0.4?

**Comment by chapa** [comment]
I did not install lorenzo/pinky explicitely, I installed twig/inky-extension which automatically install lorenzo/pinky in version 1.0.3.

Actually, I just realized that as I didn't have the ext-xsl installed, composer chose the 1.0.3 version because it matches the `^1.0` required by twig/inky-extension and 1.0.3 was the latest version compatible with my system.\
For example if I try to install twig/inky-extension with a system having the xsl-ext installed, the latest version (1.0.5 as I write these lines) is well installed.

Now I'm not sure who's responsible for doing something, maybe lorenzo/pinky shouldn't have updated the PATCH number of its version ?

The fact is, when `composer require twig/inky-extension` is run on a system without ext-xsl, there is no composer warning saying that the extension is missing, and a hardly understandable error at runtime.\
I thought upgrading pinky version of this package was the easiest solution, but maybe someone has a better idea ?

**Comment by fabpot** [comment]
Just tagged a new version with a min version of `1.0.5` (which contains an important fix as well).
